MODULE SARK_Module
USE LetaGropModule
USE L3
Implicit NONE

SAVE

CONTAINS
!-----------------------------------------------------------------------------
SUBROUTINE SARK
USE DIMS_Module, ONLY : MXK
!Integer, PARAMETER :: MXK = 40
Implicit NONE
  Real(dp) :: U1KO,U2KO,UCKO,UKO,UMINKO,KCKO(MXK),KMINKO(MXK),KVKO(MXK), &
        PINNKO(MXK),RUTAKO(MXK,MXK),SHKO(MXK,MXK),SKO(MXK,MXK),STEKKO(MXK)
  Integer :: NGEKO,NIDOKO,NKO,RIDOKO,RIKO,RJKO,SLUSKO,IDOKO(5),IVARKO(MXK),IVGEKO(MXK)
  Logical :: MINKKO,PROVKO
  Integer :: LI,LJ
  SAVE
  if(lgDbg) write(*,'("SARK in, TAGE=",L1)') TAGE
  IF(TAGE) GO TO 5
! KOUT
  TAGE=.TRUE.
  ORVAKO=ORVAR
  SLUSKO=SLUSK
  PROVKO=PROV
  MINKKO=MINK
  PROV=.FALSE.
  SLUSK=0
  UKO=0.D0
  NKO=N
  NGEKO=NGE
  NIDOKO=NIDO
  RIKO=RI
  RJKO=RJ
  RIDOKO=RIDO
  U1KO=U1
  U2KO=U2
  UCKO=UC
  UMINKO=UMIN
  if(lgDbg) write(*,'("SARK - NIDO=",I0," N=",I0," NGE=",I0)') NIDO,N,NGE
  IF(NIDO < 1) GO TO 15
  DO LI=1,NIDO
    IDOKO(LI)=IDO(LI)
  END DO
15 CONTINUE
  IF(N < 1) GO TO 21
  DO LI=1,N
    IVARKO(LI)=IVAR(LI)
    KCKO(LI)=KC(LI)
    KMINKO(LI)=KMIN(LI)
    KVKO(LI)=KV(LI)
    PINNKO(LI)=PINNE(LI)
    STEKKO(LI)=STEK(LI)
  END DO
21 CONTINUE
  IF(NGE < 1) GO TO 31
  DO LI=1,NGE
    IVGEKO(LI)=IVARGE(LI)
  END DO
31 CONTINUE
  IF(N < 1) GO TO 41
  DO LI=1,N
    DO LJ=1,N
        SKO(LI,LJ)=S(LI,LJ)
        SHKO(LI,LJ)=SH(LI,LJ)
        RUTAKO(LI,LJ)=RUTA(LI,LJ)
    END DO
  END DO
! KOUT SLUT
41 CONTINUE
  RSL = 0 ! RS=RS1-1 ! change Aug.2021
  GO TO 10100
5 CONTINUE
  RSKOTT=RSKOTT-1
  IF(RSKOTT > 0) GO TO 10200
  UKO=UKO+UMIN
! NYSA
10100 CONTINUE
  RSL = RSL+1 ! RS=RS+1 ! change Aug.2021
  if(lgDbg) write(*,'("SARK - RSL=",I0)') RSL
  RS = RSI(RSL)         ! change Aug.2021
  IF(RSL > RSN) GO TO 10300 ! IF(RS > RS2) GO TO 10300 ! change Aug.2021
  N=NIKS(RS)
  CALL SIKREN (N)
  ORVAR=0
  IF(N >= 1) THEN
    DO LI=1,N
        IVAR(LI)=VAKS(RS,LI)
    END DO
  END IF
  IF(SKRIUT > -1) CALL SKOTT
  IF(N /= 0) GO TO 8
  RSKOTT=1
  GO TO 10200
8 RSKOTT=NSKOTT
! SARKUT
10200 CONTINUE
  IF(N < 1) GO TO 91
  DO I=1,N
    IK=IVAR(I)
    CALL STEKA
    KC(I)=KS(RS,IK)
    KV(I)=KC(I)
  END DO
91 INDIC=1800
  RETURN
! SARKSLUT
10300 CONTINUE
! KOIN
  TAGE=.FALSE.
  ORVAR=ORVAKO
  SLUSK=SLUSKO
  PROV=PROVKO
  MINK=MINKKO
  N=NKO
  NGE=NGEKO
  NIDO=NIDOKO
  RI=RIKO
  RJ=RJKO
  RIDO=RIDOKO
  U=UKO
  U1=U1KO
  U2=U2KO
  UC=UCKO
  UMIN=UMINKO
  IF(NIDO >= 1) THEN
    DO LI=1,NIDO
        IDO(LI)=IDOKO(LI)
    END DO
  END IF
  IF(N < 1) GO TO 111
  DO LI=1,N
    IVAR(LI)=IVARKO(LI)
    KC(LI)=KCKO(LI)
    KMIN(LI)=KMINKO(LI)
    KV(LI)=KVKO(LI)
    PINNE(LI)=PINNKO(LI)
    STEK(LI)=STEKKO(LI)
  END DO
111 IF(NGE < 1) GO TO 121
  DO LI=1,NGE
    IVARGE(LI)=IVGEKO(LI)
  END DO
121 IF(N >= 1) THEN
    DO LI=1,N
        DO LJ=1,N
            S(LI,LJ)=SKO(LI,LJ)
            SH(LI,LJ)=SHKO(LI,LJ)
            RUTA(LI,LJ)=RUTAKO(LI,LJ)
        END DO
    END DO
  END IF
! KOIN SLUT
  IF(PROV.AND.SKRIUT > -2) CALL PROVAR
  IF(SKRIUT > -2.OR.PROV)  CALL UVAR (UT)
  IF(SKRIUT > -1) WRITE (UT,1111)
  IF(SKRIUT > -1) WRITE (*,1111)
1111  FORMAT(/39(' -')/)
  INDIC=1700
  RETURN
END SUBROUTINE SARK

END MODULE SARK_Module